# Generated by Django 4.0.1 on 2022-01-25 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField(default=datetime.datetime(2022, 1, 25, 20, 8, 48, 823670, tzinfo=utc))),
                ('date_created', models.DateField(auto_now=True)),
                ('note_type', models.CharField(choices=[('TXN', 'Text Note'), ('LSN', 'List Note'), ('LNN', 'Link Note')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TextNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_field', models.TextField(max_length=500)),
                ('note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.notedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ListNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_note', models.CharField(max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('note_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notedetails')),
            ],
        ),
        migrations.CreateModel(
            name='LinkNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_note', models.URLField()),
                ('note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.notedetails')),
            ],
        ),
    ]
