# Generated by Django 4.0.1 on 2022-01-25 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listnotes',
            name='note_details',
        ),
        migrations.AlterField(
            model_name='notedetails',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 21, 3, 18, 50057, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ListDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.listnotes')),
                ('note_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notedetails')),
            ],
        ),
    ]
