# Generated by Django 4.0.1 on 2022-01-25 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_listdetails_list_notes_listdetails_list_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedetails',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 23, 48, 27, 982579, tzinfo=utc)),
        ),
    ]
