# Generated by Django 4.0.1 on 2022-01-26 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notedetails_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedetails',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 9, 11, 46, 16969, tzinfo=utc)),
        ),
    ]
