# Generated by Django 4.0.1 on 2022-01-26 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_listdetails_note_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedetails',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 11, 29, 15, 693843, tzinfo=utc)),
        ),
    ]
