# Generated by Django 4.0.1 on 2022-01-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_alter_notedetails_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedetails',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
